### PR TITLE
Doc: Adding Quick Start Guide

### PR DESCRIPTION
**Pull request by munoz0raul**
Signed-off-by: Raul Muñoz <raul@foundries.io>

Please review and make sure the container is the same as https://foundries.io/media/events/variscite-fio-quickstart.pdf

### CODE REVIEW

**Comment by munoz0raul** [comment]
Just converted it to draft. Before merging, we need to change all the image URLs to the Foundries.io git hub.

**Comment by kprosise** [comment]
@munoz0raul I cloned your fork and I am doing copy-editing work locally, which makes it easier for me to run linters and do editing. Once finished, I can either copy the changes over as review suggestions, give you a patch, or do a PR on either repo.

**Review by kprosise — COMMENTED** [review]
Some of the inline html could be switched out for markdown, but doesn't need to be. Some additional linting could be done, but I think I suggested the ones that impact rendering. Note to get this completed in a timely manor, I was not able to check all of my suggestions, so we will want to double check out GitHub renders it prior to merging. 

there was also some suggestions regarding general style.

**Review by kprosise — APPROVED** [review]
LGTM

**Pull request merged**
